Repository SolSolHigh/SolSolHigh-BE, pull requests merged in 2024-08, with the labels that each got.

#5 [Chore/#4] spring open ai dependency 수정
  .gradle/8.8/checksums/checksums.lock
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build.gradle
  settings.gradle
Labels: 📐 Chore, 📣 Merge

#6 [Feat/#3] fcm settings
  .gradle/8.8/checksums/checksums.lock
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/com/shinhan/solsolhigh/fcm/application/FirebaseCloudMessageService.java
  src/main/java/com/shinhan/solsolhigh/fcm/config/FcmConfig.java
  src/main/java/com/shinhan/solsolhigh/fcm/domain/FcmToken.java
  src/main/resources/application.yml
Labels: ✨ Feat, 📣 Merge

#8 [Feat/#7] openai 퀴즈 생성 로직 추가
  .gradle/8.8/checksums/checksums.lock
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build.gradle
  src/main/java/com/shinhan/solsolhigh/account/query/.gitkeep
  src/main/java/com/shinhan/solsolhigh/experience/query/.gitkeep
  src/main/java/com/shinhan/solsolhigh/mission/query/.gitkeep
  src/main/java/com/shinhan/solsolhigh/promise/query/.gitkeep
  src/main/java/com/shinhan/solsolhigh/quiz/application/FinancialQuizRegisterService.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/.gitkeep
  src/main/java/com/shinhan/solsolhigh/quiz/domain/FinancialQuiz.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/FinancialQuizRepository.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/QuizKeyword.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/SelectedQuizKeyword.java
  src/main/java/com/shinhan/solsolhigh/quiz/infra/.gitkeep
  src/main/java/com/shinhan/solsolhigh/quiz/infra/AddQuizDto.java
  src/main/java/com/shinhan/solsolhigh/quiz/infra/QuizAiChat.java
  src/main/java/com/shinhan/solsolhigh/quiz/query/RequestFinancialQuizService.java
  src/main/java/com/shinhan/solsolhigh/springconfig/.gitkeep
  src/main/java/com/shinhan/solsolhigh/user/domain/Child.java
  src/main/java/com/shinhan/solsolhigh/user/domain/ChildRepository.java
  src/main/java/com/shinhan/solsolhigh/user/domain/Gender.java
  src/main/java/com/shinhan/solsolhigh/user/domain/GenderConverter.java
  src/main/java/com/shinhan/solsolhigh/user/domain/User.java
  src/main/java/com/shinhan/solsolhigh/user/query/.gitkeep
  src/main/java/com/shinhan/solsolhigh/user/service/.gitkeep
  src/test/java/com/shinhan/solsolhigh/quiz/infra/QuizAiChatTest.java
Labels: ✨ Feat, 📣 Merge, 📜 Test

#11 [Chore/#10] docker-compose Redis 추가
  docker-compose.yml
Labels: 📐 Chore

#14 [Feat/#13] Redis Session 설정
  .gitignore
  src/main/java/com/shinhan/solsolhigh/redis/config/RedisConfig.java
  src/main/java/com/shinhan/solsolhigh/session/config/SessionConfig.java
  src/main/resources/application.yml
Labels: ✨ Feat

#17 [Chore#16] .gradle 삭제
  .gradle/8.8/checksums/checksums.lock
  .gradle/8.8/dependencies-accessors/gc.properties
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileChanges/last-build.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
Labels: 📐 Chore

#19 [Feat#15] Spring Security - OAuth2
  build.gradle
  src/main/java/com/shinhan/solsolhigh/auth/application/CustomOAuthUserService.java
  src/main/java/com/shinhan/solsolhigh/auth/application/KakaoOAuthResponse.java
  src/main/java/com/shinhan/solsolhigh/auth/application/NaverOAuthResponse.java
  src/main/java/com/shinhan/solsolhigh/auth/application/OAuthResponse.java
  src/main/java/com/shinhan/solsolhigh/common/exception/ErrorConstantDefinition.java
  src/main/java/com/shinhan/solsolhigh/redis/config/RedisConfig.java
  src/main/java/com/shinhan/solsolhigh/security/config/OAuthLoginFailureExceptionHandler.java
  src/main/java/com/shinhan/solsolhigh/security/config/SecurityConfig.java
  src/main/java/com/shinhan/solsolhigh/session/config/SessionConfig.java
  src/main/java/com/shinhan/solsolhigh/session/config/SessionConstants.java
  src/main/java/com/shinhan/solsolhigh/user/domain/Gender.java
  src/main/java/com/shinhan/solsolhigh/user/domain/GenderConverter.java
  src/main/java/com/shinhan/solsolhigh/user/domain/User.java
  src/main/java/com/shinhan/solsolhigh/user/domain/UserRepository.java
  src/main/java/com/shinhan/solsolhigh/user/exception/UserErrorConstants.java
  src/main/java/com/shinhan/solsolhigh/user/exception/UserSignupNotCompletedException.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
Labels: ✨ Feat

#22 [Feat/#18] 미션 도메인 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/shinhan/solsolhigh/mission/application/.gitkeep
  src/main/java/com/shinhan/solsolhigh/mission/application/MissionRegisterRequest.java
  src/main/java/com/shinhan/solsolhigh/mission/application/MissionRegisterService.java
  src/main/java/com/shinhan/solsolhigh/mission/application/MissionRemoveService.java
  src/main/java/com/shinhan/solsolhigh/mission/application/MissionUpdateRequest.java
  src/main/java/com/shinhan/solsolhigh/mission/application/MissionUpdateService.java
  src/main/java/com/shinhan/solsolhigh/mission/domain/Mission.java
  src/main/java/com/shinhan/solsolhigh/mission/domain/MissionData.java
  src/main/java/com/shinhan/solsolhigh/mission/domain/MissionDataRepository.java
  src/main/java/com/shinhan/solsolhigh/mission/domain/MissionRepository.java
  src/main/java/com/shinhan/solsolhigh/mission/exception/MissionAccessException.java
  src/main/java/com/shinhan/solsolhigh/mission/exception/MissionExceptionConstants.java
  src/main/java/com/shinhan/solsolhigh/mission/exception/MissionNotFoundException.java
  src/main/java/com/shinhan/solsolhigh/mission/query/MissionFindService.java
  src/main/java/com/shinhan/solsolhigh/mission/query/MissionValidCheckService.java
  src/main/java/com/shinhan/solsolhigh/mission/ui/MissionController.java
  src/main/java/com/shinhan/solsolhigh/mission/ui/dto/MissionView.java
  src/main/java/com/shinhan/solsolhigh/user/domain/ChildRepository.java
  src/main/java/com/shinhan/solsolhigh/user/exception/FamilyNotExistException.java
  src/main/java/com/shinhan/solsolhigh/user/exception/UserErrorConstants.java
  src/main/java/com/shinhan/solsolhigh/user/query/FamilyCheckService.java
  src/test/java/com/shinhan/solsolhigh/mission/application/MissionRegisterServiceTest.java
  src/test/java/com/shinhan/solsolhigh/mission/domain/MissionDataRepositoryTest.java
  src/test/java/com/shinhan/solsolhigh/mission/domain/MissionTest.java
Labels: ✨ Feat, 📣 Merge, 📜 Test

#24 [Feat/#23] 퀴즈 도메인 기능 추가
  src/main/java/com/shinhan/solsolhigh/quiz/application/.gitkeep
  src/main/java/com/shinhan/solsolhigh/quiz/application/BetweenOfDayQuizSolveLogUpdater.java
  src/main/java/com/shinhan/solsolhigh/quiz/application/FinancialQuizRegisterService.java
  src/main/java/com/shinhan/solsolhigh/quiz/application/FinancialQuizSolveService.java
  src/main/java/com/shinhan/solsolhigh/quiz/application/SelectedQuizKeywordRegisterService.java
  src/main/java/com/shinhan/solsolhigh/quiz/application/dto/QuizSolveRequest.java
  src/main/java/com/shinhan/solsolhigh/quiz/application/dto/SelectedQuizKeywordDto.java
  src/main/java/com/shinhan/solsolhigh/quiz/application/dto/SelectedQuizKeywordRemoveService.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/BetweenOfDatQuizSolveLog.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/BetweenOfDayQuizSolveLog.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/FinancialQuiz.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/FinancialQuizRepository.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/QuizKeyword.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/QuizSolve.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/SelectedQuizKeyword.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/repository/BetweenOfDayQuizSolveLogRepository.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/repository/FinancialQuizRepository.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/repository/QuizKeywordRepository.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/repository/QuizSolveRepository.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/repository/SelectedQuizKeywordRepository.java
  src/main/java/com/shinhan/solsolhigh/quiz/domain/support/QuizSolveSupport.java
  src/main/java/com/shinhan/solsolhigh/quiz/exception/FinancialQuizNotFoundException.java
  src/main/java/com/shinhan/solsolhigh/quiz/exception/QuizExceptionConstants.java
  src/main/java/com/shinhan/solsolhigh/quiz/exception/QuizKeywordNotFoundException.java
  src/main/java/com/shinhan/solsolhigh/quiz/exception/QuizSolveExistException.java
  src/main/java/com/shinhan/solsolhigh/quiz/exception/SelectedQuizCountOverException.java
  src/main/java/com/shinhan/solsolhigh/quiz/exception/SelectedQuizExistException.java
  src/main/java/com/shinhan/solsolhigh/quiz/exception/SelectedQuizNotFoundException.java
  src/main/java/com/shinhan/solsolhigh/quiz/infra/QuizAiChat.java
  src/main/java/com/shinhan/solsolhigh/quiz/query/BetweenOfDayQuizSolveLogFindService.java
  src/main/java/com/shinhan/solsolhigh/quiz/query/FinancialQuizFindService.java
  src/main/java/com/shinhan/solsolhigh/quiz/query/QuizKeywordFindService.java
  src/main/java/com/shinhan/solsolhigh/quiz/query/QuizSolveFindService.java
  src/main/java/com/shinhan/solsolhigh/quiz/query/RequestFinancialQuizService.java
  src/main/java/com/shinhan/solsolhigh/quiz/query/SelectedQuizKeywordFindService.java
  src/main/java/com/shinhan/solsolhigh/quiz/ui/KeywordController.java
  src/main/java/com/shinhan/solsolhigh/quiz/ui/QuizController.java
  src/main/java/com/shinhan/solsolhigh/quiz/ui/StrickController.java
  src/main/java/com/shinhan/solsolhigh/quiz/ui/dto/KeywordView.java
  src/main/java/com/shinhan/solsolhigh/quiz/ui/dto/QuizAnswerView.java
  src/main/java/com/shinhan/solsolhigh/quiz/ui/dto/QuizSolveView.java
  src/main/java/com/shinhan/solsolhigh/quiz/ui/dto/QuizView.java
  src/main/java/com/shinhan/solsolhigh/quiz/ui/dto/SolveStrickView.java
  src/main/java/com/shinhan/solsolhigh/user/exception/FamilyNotExistException.java
  src/main/resources/schema.sql
Labels: ✨ Feat, 📣 Merge

#28 [Feat/#25] s3 config
  build.gradle
  src/main/java/com/shinhan/solsolhigh/common/util/UUIDGenerator.java
  src/main/java/com/shinhan/solsolhigh/s3/config/S3config.java
  src/main/java/com/shinhan/solsolhigh/s3/upload/S3Uploader.java
Labels: ✨ Feat, 📣 Merge

#33 [Fix/#32] 유저 인증 UUID 추가
  src/main/java/com/shinhan/solsolhigh/auth/application/CustomOAuthUserService.java
  src/main/java/com/shinhan/solsolhigh/security/config/CustomAuthenticationFailureHandler.java
  src/main/java/com/shinhan/solsolhigh/security/config/CustomAuthenticationSuccessHandler.java
  src/main/java/com/shinhan/solsolhigh/security/config/SecurityConfig.java
  src/main/java/com/shinhan/solsolhigh/springconfig/ServerConfig.java
  src/main/java/com/shinhan/solsolhigh/user/application/UserService.java
  src/main/java/com/shinhan/solsolhigh/user/application/UserSignupDto.java
  src/main/java/com/shinhan/solsolhigh/user/domain/TemporaryUser.java
  src/main/java/com/shinhan/solsolhigh/user/domain/TemporaryUserRepository.java
  src/main/java/com/shinhan/solsolhigh/user/ui/request/UserSignupRequest.java
  src/main/resources/schema.sql
Labels: 🔧 Fix, 💥 Bug

#34 [Feat/#27] 약속권 도메인 기능 추가
  .gitignore
  src/main/java/com/shinhan/solsolhigh/promise/application/.gitkeep
  src/main/java/com/shinhan/solsolhigh/promise/application/PromiseTicketInfo.java
  src/main/java/com/shinhan/solsolhigh/promise/application/PromiseTicketService.java
  src/main/java/com/shinhan/solsolhigh/promise/application/PromiseTicketUnusedCountByChildDto.java
  src/main/java/com/shinhan/solsolhigh/promise/application/PromiseTicketUseDto.java
  src/main/java/com/shinhan/solsolhigh/promise/application/PromiseTicketUseRequestDto.java
  src/main/java/com/shinhan/solsolhigh/promise/application/PromiseTicketUsedByIdDto.java
  src/main/java/com/shinhan/solsolhigh/promise/application/PromiseTicketUsedByNicknameDto.java
  src/main/java/com/shinhan/solsolhigh/promise/domain/PromiseTicket.java
  src/main/java/com/shinhan/solsolhigh/promise/domain/PromiseTicketRepository.java
  src/main/java/com/shinhan/solsolhigh/promise/domain/PromiseTicketUsedLog.java
  src/main/java/com/shinhan/solsolhigh/promise/exception/PromiseTicketAlreadyRequestedException.java
  src/main/java/com/shinhan/solsolhigh/promise/exception/PromiseTicketAlreadyUsedException.java
  src/main/java/com/shinhan/solsolhigh/promise/exception/PromiseTicketDescriptionMismatchException.java
  src/main/java/com/shinhan/solsolhigh/promise/exception/PromiseTicketErrorConstants.java
  src/main/java/com/shinhan/solsolhigh/promise/exception/PromiseTicketImageMismatchException.java
  src/main/java/com/shinhan/solsolhigh/promise/exception/PromiseTicketNotExistsException.java
  src/main/java/com/shinhan/solsolhigh/promise/exception/PromiseTicketNotFoundException.java
  src/main/java/com/shinhan/solsolhigh/promise/exception/PromiseTicketNotRequestedException.java
  src/main/java/com/shinhan/solsolhigh/promise/ui/PromiseTicketController.java
  src/main/java/com/shinhan/solsolhigh/promise/ui/request/PromiseTicketUseRequestRequest.java
  src/main/java/com/shinhan/solsolhigh/promise/ui/response/PromiseTicketUnusedCountResponse.java
  src/main/java/com/shinhan/solsolhigh/promise/validation/annotation/PromiseTicketDescription.java
  src/main/java/com/shinhan/solsolhigh/promise/validation/annotation/PromiseTicketImage.java
  src/main/java/com/shinhan/solsolhigh/promise/validation/validator/PromiseTicketDescriptionValidator.java
  src/main/java/com/shinhan/solsolhigh/promise/validation/validator/PromiseTicketImageValidator.java
  src/main/java/com/shinhan/solsolhigh/s3/exception/ImageUploadFailException.java
  src/main/java/com/shinhan/solsolhigh/s3/exception/S3ErrorConstants.java
  src/main/java/com/shinhan/solsolhigh/s3/upload/S3Uploader.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
Labels: ✨ Feat

#39 [Fix/#38] deleteTrade Pathvariable 닫는 괄호 없음 수정
  src/main/java/com/shinhan/solsolhigh/egg/ui/MarketController.java
Labels: 🔧 Fix, 📣 Merge, 💥 Bug

#44 [Feat/#43] notification
  src/main/java/com/shinhan/solsolhigh/egg/application/EggHitCountUpdateService.java
  src/main/java/com/shinhan/solsolhigh/egg/application/EggSellBoardBuyService.java
  src/main/java/com/shinhan/solsolhigh/egg/ui/EggController.java
  src/main/java/com/shinhan/solsolhigh/egg/ui/dto/EggSellBoardView.java
  src/main/java/com/shinhan/solsolhigh/egg/ui/dto/HoldSpecialEggView.java
  src/main/java/com/shinhan/solsolhigh/egg/ui/dto/SpecialEggView.java
  src/main/java/com/shinhan/solsolhigh/fcm/domain/Fcm.java
  src/main/java/com/shinhan/solsolhigh/fcm/domain/FcmRepository.java
  src/main/java/com/shinhan/solsolhigh/fcm/infra/FirebaseCloudMessageService.java
  src/main/java/com/shinhan/solsolhigh/mission/domain/Mission.java
  src/main/java/com/shinhan/solsolhigh/notification/application/NotificationRegisterRequest.java
  src/main/java/com/shinhan/solsolhigh/notification/application/NotificationRegisterService.java
  src/main/java/com/shinhan/solsolhigh/notification/config/NotificationAsyncConfig.java
  src/main/java/com/shinhan/solsolhigh/notification/domain/NotificationLog.java
  src/main/java/com/shinhan/solsolhigh/notification/domain/NotificationLogRepository.java
  src/main/java/com/shinhan/solsolhigh/notification/domain/NotificationType.java
  src/main/java/com/shinhan/solsolhigh/notification/infra/NotificationRequestedEvent.java
  src/main/java/com/shinhan/solsolhigh/notification/infra/NotificationSendHandler.java
  src/main/java/com/shinhan/solsolhigh/notification/query/NotificationLogFindService.java
  src/main/java/com/shinhan/solsolhigh/notification/ui/NotificationController.java
  src/main/java/com/shinhan/solsolhigh/notification/ui/NotificationView.java
  src/main/java/com/shinhan/solsolhigh/promise/application/PromiseTicketService.java
  src/main/java/com/shinhan/solsolhigh/user/application/UserService.java
  src/main/resources/schema.sql
Labels: ✨ Feat, 📣 Merge

#47 [Fix/#46] schema.sql 수정
  src/main/resources/schema.sql
Labels: 🔧 Fix, 📣 Merge, 💥 Bug

#49 [Chore/#48] 더미데이터 추가
  src/main/java/com/shinhan/solsolhigh/fcm/application/FcmRegisterService.java
  src/main/java/com/shinhan/solsolhigh/fcm/domain/FcmRepository.java
  src/main/resources/schema.sql
Labels: 📐 Chore, 📣 Merge

#51 [Feat/#50] dalle3 이미지 생성 로직 추가
  README.md
  src/main/java/com/shinhan/solsolhigh/fcm/infra/FirebaseCloudMessageService.java
  src/main/java/com/shinhan/solsolhigh/user/infra/ProductAiChat.java
  src/main/java/com/shinhan/solsolhigh/user/infra/ProductAiDraw.java
  src/main/java/com/shinhan/solsolhigh/user/infra/ProductRecommendDto.java
  src/test/java/com/shinhan/solsolhigh/mission/application/MissionRegisterServiceTest.java
  src/test/java/com/shinhan/solsolhigh/user/infra/ProductAiChatTest.java
  src/test/java/com/shinhan/solsolhigh/user/infra/ProductAiDrawTest.java
Labels: ✨ Feat, 📣 Merge

#54 [Chore/#52] dummy data 구축
  src/main/resources/schema.sql
Labels: 📐 Chore, 📣 Merge

#55 [Chore/#45] readme
  Dockerfile
  README.md
  docs/Redis-Light.svg
  docs/icons8-chatgpt-50.svg
  docs/icons8-mysql.svg
  docs/springboot-color.svg
  src/main/java/com/shinhan/solsolhigh/quiz/domain/repository/QuizSolveRepository.java
  src/main/java/com/shinhan/solsolhigh/quiz/ui/StrickController.java
  src/main/resources/schema.sql
Labels: 📐 Chore, 📣 Merge
